[tool.pytest.ini_options]
addopts = "--tb native -v -r fxX --maxfail=100 -p no:warnings --log-info=sqlalchemy.engine "

markers = [
     "backend: mark test as for the backend",
]

python_files = "test/*test_*.py"

# SQLAlchemy-Firebird configuration for Black.

[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.github
  | \.pytest_cache
  | _venv
)/
'''
